"""add attendance and timesheet tables

Stage 10. Two new tables, and one column added to an existing one.

`attendance` answers "was this person here, and for how long?". One row per
employee per day, enforced by a unique constraint rather than by a check in
the service, so two browser tabs racing to check in produce one row and one
error. `worked_minutes` is derived from the two timestamps but stored, because
every dashboard figure sums it across many rows and one stored definition beats
recomputing a difference in several places.

`timesheets` answers "what work did they record, and was it approved?". It is
kept separate from attendance on purpose: the two disagreeing is useful
information, and merging them would make "present, but nothing logged"
impossible to express. It carries `workflow_id` and `current_state_id` instead
of a status column, so it is driven by the Stage 7 engine with no change to
that engine. There is no unique constraint on (employee, date) - a day is
normally several pieces of work, each approved on its own merits.

`workflow_states.is_owner_held` is the one change to existing infrastructure.
The engine answers "which roles may perform this transition?"; an application
usually also needs "and is this caller the right person?" - a manager may
approve timesheets, but not their own. Stage 9 inferred that from
`is_initial`, which works only while every owner action leaves the first
state. The timesheet workflow breaks that, because REJECTED -> DRAFT (Revise)
is the author's action and REJECTED is not initial. Marking the *state* as
owner-held states the fact directly and generalises: a transition out of an
owner-held state belongs to the record's owner, whatever it is called.

The column defaults to false, so every existing workflow keeps its current
behaviour until the seed marks the states that are genuinely owner-held.

Revision ID: 38b012a1140b
Revises: 6c89d0992c9b
Create Date: 2026-09-16 10:42:27.610711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b012a1140b'
down_revision: Union[str, Sequence[str], None] = '6c89d0992c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=True),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_day')
    )
    op.create_index(op.f('ix_attendance_attendance_date'), 'attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_attendance_status'), 'attendance', ['attendance_status'], unique=False)
    op.create_index('ix_attendance_employee_date', 'attendance', ['employee_id', 'attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_table('timesheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('work_description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('current_state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_state_id'], ['workflow_states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheets_current_state_id'), 'timesheets', ['current_state_id'], unique=False)
    op.create_index('ix_timesheets_employee_date', 'timesheets', ['employee_id', 'work_date'], unique=False)
    op.create_index(op.f('ix_timesheets_employee_id'), 'timesheets', ['employee_id'], unique=False)
    op.create_index(op.f('ix_timesheets_work_date'), 'timesheets', ['work_date'], unique=False)
    op.create_index(op.f('ix_timesheets_workflow_id'), 'timesheets', ['workflow_id'], unique=False)
    op.add_column('workflow_states', sa.Column('is_owner_held', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_states', 'is_owner_held')
    op.drop_index(op.f('ix_timesheets_workflow_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_work_date'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_employee_id'), table_name='timesheets')
    op.drop_index('ix_timesheets_employee_date', table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_current_state_id'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index('ix_attendance_employee_date', table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_date'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
