"""add workflow engine tables

Revision ID: 3f0f32d0eba7
Revises: 1c4b1324dd39
Create Date: 2026-09-11 16:26:50.592125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0f32d0eba7'
down_revision: Union[str, Sequence[str], None] = '1c4b1324dd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_workflows_application_id'), 'workflows', ['application_id'], unique=False)
    op.create_table('workflow_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_initial', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'code', name='uq_workflow_states_code')
    )
    op.create_index(op.f('ix_workflow_states_workflow_id'), 'workflow_states', ['workflow_id'], unique=False)
    op.create_table('workflow_demo_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('current_state_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_state_id'], ['workflow_states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_demo_requests_created_by_user_id'), 'workflow_demo_requests', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_workflow_demo_requests_current_state_id'), 'workflow_demo_requests', ['current_state_id'], unique=False)
    op.create_index(op.f('ix_workflow_demo_requests_workflow_id'), 'workflow_demo_requests', ['workflow_id'], unique=False)
    op.create_table('workflow_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('from_state_id', sa.Integer(), nullable=False),
    sa.Column('to_state_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_state_id'], ['workflow_states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_state_id'], ['workflow_states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'code', name='uq_workflow_transitions_code')
    )
    op.create_index(op.f('ix_workflow_transitions_from_state_id'), 'workflow_transitions', ['from_state_id'], unique=False)
    op.create_index(op.f('ix_workflow_transitions_to_state_id'), 'workflow_transitions', ['to_state_id'], unique=False)
    op.create_index(op.f('ix_workflow_transitions_workflow_id'), 'workflow_transitions', ['workflow_id'], unique=False)
    op.create_table('workflow_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('from_state_id', sa.Integer(), nullable=True),
    sa.Column('to_state_id', sa.Integer(), nullable=False),
    sa.Column('transition_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_state_id'], ['workflow_states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_state_id'], ['workflow_states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transition_id'], ['workflow_transitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_history_entity', 'workflow_history', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_history_performed_by_user_id'), 'workflow_history', ['performed_by_user_id'], unique=False)
    op.create_index(op.f('ix_workflow_history_workflow_id'), 'workflow_history', ['workflow_id'], unique=False)
    op.create_table('workflow_transition_roles',
    sa.Column('transition_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transition_id'], ['workflow_transitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transition_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_transition_roles')
    op.drop_index(op.f('ix_workflow_history_workflow_id'), table_name='workflow_history')
    op.drop_index(op.f('ix_workflow_history_performed_by_user_id'), table_name='workflow_history')
    op.drop_index('ix_workflow_history_entity', table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_workflow_transitions_workflow_id'), table_name='workflow_transitions')
    op.drop_index(op.f('ix_workflow_transitions_to_state_id'), table_name='workflow_transitions')
    op.drop_index(op.f('ix_workflow_transitions_from_state_id'), table_name='workflow_transitions')
    op.drop_table('workflow_transitions')
    op.drop_index(op.f('ix_workflow_demo_requests_workflow_id'), table_name='workflow_demo_requests')
    op.drop_index(op.f('ix_workflow_demo_requests_current_state_id'), table_name='workflow_demo_requests')
    op.drop_index(op.f('ix_workflow_demo_requests_created_by_user_id'), table_name='workflow_demo_requests')
    op.drop_table('workflow_demo_requests')
    op.drop_index(op.f('ix_workflow_states_workflow_id'), table_name='workflow_states')
    op.drop_table('workflow_states')
    op.drop_index(op.f('ix_workflows_application_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
