"""add leave management tables

Two tables for Stage 9.

`leave_types` is configuration: the kinds of leave the organisation offers,
as rows rather than a Python enum, so adding one is an INSERT.

`leave_requests` is the business record, and the interesting part is what it
does *not* contain. There is no status column. Instead it carries the two
foreign keys the generic workflow engine requires - workflow_id and
current_state_id - so the states a request can be in, and who may move it
between them, live in the Stage 7 workflow tables. That is why this migration
adds no leave-specific approval or history table: workflow_history already
records what happens to any entity by (entity_type, entity_id).

Every foreign key is RESTRICT. Deleting a leave type, an employee, a workflow
or a state that a request still points at should fail loudly rather than
quietly cut a record loose from its own history.

Revision ID: 6c89d0992c9b
Revises: 8af9430c31c4
Create Date: 2026-09-15 09:57:24.967845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c89d0992c9b'
down_revision: Union[str, Sequence[str], None] = '8af9430c31c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('current_state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_state_id'], ['workflow_states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_current_state_id'), 'leave_requests', ['current_state_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_leave_type_id'), 'leave_requests', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_workflow_id'), 'leave_requests', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_requests_workflow_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_leave_type_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_current_state_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
