"""add expense management tables

Stage 11. Three new tables, and one column added to an existing one.

`expense_categories` is configuration - Travel, Meals, Hotel - as rows, so
adding one is an INSERT rather than a code change. Categories are carried and
grouped, never branched on, which is what makes a table the right home for
them; attendance statuses stayed a Python tuple for exactly the opposite
reason.

`expenses` carries `workflow_id` and `current_state_id` instead of a status
column, so it is driven by the Stage 7 engine with no change to that engine.
`amount` is **Numeric(12, 2), never Float**: a binary float cannot represent
0.10 exactly, and summing a few hundred of them drifts away from the figure a
person gets on paper. Money that does not reconcile is worse than no money.

`expense_attachments` stores metadata only; the bytes live on disk outside the
database and outside git. It keeps two names for the same file - `file_name`
is what the person called it and is only displayed, `stored_name` is what the
server called it and is the only thing used to build a path. That split is the
security boundary: a browser can upload something called "../../../etc/passwd"
and the server must never let that string reach the filesystem.

`workflow_transitions.actor` is the one change to existing infrastructure. The
engine answers "which roles may perform this transition?"; an application also
needs "and is this caller the right person?". Stage 9 inferred that from
`is_initial`, Stage 10 moved it to the from-state's `is_owner_held`, and this
stage moves it onto the transition - because the two can genuinely disagree.
An expense in SUBMITTED sits on the approver's desk, so the pending queue is
right to treat that state as theirs, and yet Cancel - the claimant withdrawing
their own claim - leaves that same state and belongs to the owner. Only a
per-transition marker can say both things at once.

It defaults to 'ANY', so every existing workflow keeps its current behaviour
until the seed marks the transitions that genuinely belong to one side.

Revision ID: aab477092eec
Revises: 38b012a1140b
Create Date: 2026-09-16 11:34:26.606558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab477092eec'
down_revision: Union[str, Sequence[str], None] = '38b012a1140b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('current_state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_state_id'], ['workflow_states.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_current_state_id'), 'expenses', ['current_state_id'], unique=False)
    op.create_index('ix_expenses_employee_date', 'expenses', ['employee_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_employee_id'), 'expenses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_workflow_id'), 'expenses', ['workflow_id'], unique=False)
    op.create_table('expense_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_expense_attachments_expense_id'), 'expense_attachments', ['expense_id'], unique=False)
    op.add_column('workflow_transitions', sa.Column('actor', sa.String(length=10), server_default='ANY', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_transitions', 'actor')
    op.drop_index(op.f('ix_expense_attachments_expense_id'), table_name='expense_attachments')
    op.drop_table('expense_attachments')
    op.drop_index(op.f('ix_expenses_workflow_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_employee_id'), table_name='expenses')
    op.drop_index('ix_expenses_employee_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_current_state_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
